NSDictionary *errorMap = @{@"service_not_found": @"找不到请求的服务",
                               @"invalid_login_info": @"邮箱或密码错误",
                               @"invalid_request_data": @"找不到请求的数据",
                               @"invalid_refresh_token": @"找不到请求的服务",
                               @"resource_not_found": @"文件不存在",
                               @"resource_access_denied": @"操作失败，请联系邀请⼈或云方客服",
                               @"register_device_token_denied": @"注册设备授权失败",
                               @"refresh_auth_token_denied": @"刷新鉴定授权失败",
                               @"bad_api_resource": @"资源错误",
                               @"bad_api_resource_action": @"错误的接口资源请求",
                               @"bad_resource_id": @"错误的资源ID",
                               @"authentication_failed": @"鉴定失败",
                               @"auth_token_expired": @"鉴定授权已过期",
                               @"bad_api_query_param": @"接口查询参数错误",
                               @"failed_to_process_request": @"请求失败",
                               @"user_input_validation_error": @"用户输入验证失败",
                               @"item_name_conflicted": @"文件名冲突",
                               @"action_permission_denied": @"当前用户无权执行此操作",
                               @"nothing_to_update": @"无更新",
                               @"action_validation_error": @"操作鉴定失败",
                               @"share_link_alias_exists": @"分享链接自定义字段已存在",
                               @"share_link_invalid_due_time": @"无效的分享链接过期日期",
                               @"comment_invalid_mentioned_users": @"无效的评论@提及人",
                               @"user_profile_pic_upload_failure": @"用户头像上传失败",
                               @"preview_not_supported": @"当前文件类型不支持预览",
                               @"review_name_too_long": @"审阅标题过长",
                               @"item_parent_missing": @"原所在文件夹不存在，文件（夹）已经被还原至根目录",
                               @"share_link_not_found": @"此分享已失效，请联系分享人",
                               @"share_link_expired": @"该分享已过期，请联系分享人",
                               @"share_link_invalid_password": @"密码错误",
                               @"share_link_password_required": @"请输入密码",
                               @"share_link_access_denied": @"没有查看链接的权限",
                               @"collab_invitation_already_answered": @"已接受协作邀请",
                               @"invalid_share_link_verification_code": @"无效的分享链接",
                               @"user_not_found": @"没有找到该用户",
                               @"user_not_active": @"用户未激活,请先登录邮箱进行激活",
                               @"collab_not_found": @"协作关系已失效",
                               @"share_link_not_found": @"分享链接不存在",
                               @"item_name_conflicted": @"文件名已存在",
                               @"length_is_too_long":@"文件名太长",
                               @"invalid_item_name":@"文件名格式不对",
                               @"item_name_not_empty":@"文件名不能为空",
                               @"folder_name_not_empty":@"文件夹名不能为空",
                               @"item_not_deleted":@"文件/文件夹已删除",
                               @"review_invited_users_not_empty": @"请选择审阅人",
                               @"review_name_not_empty": @"请填写标题",
                               @"share_link_receivers_not_empty": @"请选择接收分享链接的用户",
                               @"item_not_found": @"文件/文件夹不存在",
                               @"user_email_not_empty": @"邮箱不能为空",
                               @"user_phone_not_empty": @"用户手机号不能为空",
                               @"invalid_email":@"请输入有效的邮箱",
                               @"incorrect_mobile_number":@"请输入有效的手机号",
                               @"user_name_not_empty":@"姓名不能为空",
                               @"invalid_user_name":@"用户名不能包含以下字符 \\ / ? : * \" ' > < |",
                               @"user_password_not_empty":@"密码不能为空"
                               };
    return errorMap[self];